### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by jacobvr** [VicShcherbert/HTMLLibrary#7]
- [x] Read about `window.localStorage`, how to set and get items from it (note the `type` of the value, it should be **string**)
- [x] Find it in your dev tools, there's a place for it
- [x] Try setting and getting some random stuff in your browser
- [x] When you understand how it works, go to your `submit` event listener and after you push, you will add a line of code that will set an item to local storage with a key `localBooksData` and value of **stringified** JSON (read about it) with your updated books array. See that it sets properly in dev tools.
- [x] At the top of the file get the item from the local storage.
- [x] Then parse JSON string and log it to see if it's right.
- [x] Instead of `books` being `const` make it `let` because you will change it, and set it to an empty array.
- [x] If value of parsed JSON exists, and if it's an array (read how to check that) then set it to `books` variable, otherwise it will stay empty array as is

**Comment by VicShcherbert** [comment]
@jacobvr Hey it works when there's already an array that exists. What if I want to start from scratch? I'm setting let books = <the JSON.stringify part>, but since there's nothing in the localStorage, it's not returning anything. How can I solve this problem?

**Comment by jacobvr** [comment]
@VicShcherbert I usually `let books = [];` at the very beginning and if local storage has something for me, I would parse and overwrite. Otherwise that check will be skipped and `books` will be `[]` as you declared before

**Comment by VicShcherbert** [comment]
@jacobvr It works! Here's how I did it: I checked if the getItem was returning anything, and if it wasnt null, it would set books to the JSON.parse(...)
<img width="574" alt="image" src="https://user-images.githubusercontent.com/65561427/164777596-8c3a976e-28b8-475f-9ac4-2657e3021da0.png">

**Comment by jacobvr** [comment]
Great, that's how it was to be done :) Also I would suggest to call it `localStorageBooks` instead of `check`, also parsing it right there on that second like, and then read more about `Array.isArray` to make sure you are not putting some corrupt data into your books after getting it from local storage. Basically, I would check if `localStorageBooks` is not `null` and if it is an array, and only then assign it.
