### ISSUE TITLE
ID for books

### ISSUE THREAD

**Issue by jacobvr** [VicShcherbert/HTMLLibrary#8]
- Soon we will need to delete and edit things in our books array, so let's prepare for that.
- In order to know what to edit, we need to have an `id` for each element in your array.
- This is not the best solution, but it will work for now. Let's use `Date.now()` which returns milliseconds from some set time in JS (you can read more about `Date` object in JS).
- So when you add an item to your array on `submit` event, among other props that you add your `values` object, let's add one more: `id: Date.now(),` and you are good to go

**Comment by VicShcherbert** [comment]
@jacobvr Alright, done with that, and also I gave the previous array elements ids as well
<img width="665" alt="Screen Shot 2022-04-25 at 11 03 02 AM" src="https://user-images.githubusercontent.com/65561427/165147482-ebdbfd72-c478-4d80-a319-0da867754f7d.png">
!
